# Generated by Django 4.0.8 on 2022-11-26 11:56

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('articles', '0005_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tage',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
