# Generated by Django 4.0.8 on 2022-11-26 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_tage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tage',
            new_name='tags',
        ),
    ]
